service: www-javed-dev

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    APP_BUCKET_NAME: www.javed.dev

resources:
  Resources:
    AppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.APP_BUCKET_NAME}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
