version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    default_reviewers:
      - "akhtarja"
    default_assignees:
      - "akhtarja"
  - package_manager: "javascript"
    directory: "/app"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    default_reviewers:
      - "akhtarja"
    default_assignees:
      - "akhtarja"
  - package_manager: "javascript"
    directory: "/now-playing"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    default_reviewers:
      - "akhtarja"
    default_assignees:
      - "akhtarja"
