service: www-javed-dev-now-playing

plugins:
  - NowPlayingDeploymentPlugin

custom:
  namespace: www-javed-dev-now-playing-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}
  config_path: "../app/js/config"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  profile: www-javed-dev
  environment:
    API_URL: ${env:WWW_JAVED_DEV_SPOTIFY_NOW_PLAYING_URL}
    API_KEY: ${env:WWW_JAVED_DEV_SPOTIFY_NOW_PLAYING_KEY}

functions:
  now-playing:
    name: ${self:custom.namespace}
    handler: handler.nowPlaying
    events:
      - http:
          path: nowplaying
          method: get
          cors: true
