name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install dependencies
        run: npm install
      - name: Deploy now-playing
        run: |
          cd now-playing
          npm install
          serverless deploy --stage prod
        env:
          WWW_JAVED_DEV_SPOTIFY_NOW_PLAYING_URL: ${{ secrets.WWW_JAVED_DEV_SPOTIFY_NOW_PLAYING_URL }}
          WWW_JAVED_DEV_SPOTIFY_NOW_PLAYING_KEY: ${{ secrets.WWW_JAVED_DEV_SPOTIFY_NOW_PLAYING_KEY }}
          WWW_JAVED_DEV_NOWPLAYING_API_CUSTOM_URL: ${{ secrets.WWW_JAVED_DEV_NOWPLAYING_API_CUSTOM_URL }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Build app
        run: |
          cd app
          npm install
          npm run build
      - name: Deploy app
        run: |
          cd app
          serverless deploy --stage prod
          npm run deploy:ci
          npm run invalidate
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_PAGER: ''
